### ISSUE TITLE
Any plans for a release ?

### ISSUE THREAD

**Issue by swiftsolves-msft** [microsoft/KqlTools#4]
Are there any plans for a release to just download rather than compile and build ?

**Comment by swiftsolves-msft** [comment]
I was able to make a build without errors | but when testing the tooling seems incomplete on --help and other commands just refers me back to --help

![image](https://user-images.githubusercontent.com/30509195/95246408-70b75b00-07e2-11eb-8069-e96c665ef386.png)

**Comment by jomorri** [comment]
I have added build command in Readme.md.

You need to build using the following command from the sources folder, dotnet build KqlTools.sln -r win-x64

Thanks,
Jose
